app/models/post.py
from uuid import uuid4
from sqlalchemy.dialects.postgresql import UUID
from enum import Enum

from app import db


class PostStatus(Enum):
    PENDING = "Pending"
    APPROVED = "Approved"
    REJECTED = "Rejected"
    UNREAD_APPROVED = "Unread_approved"
    UNREAD_REJECTED = "Unread_rejected"


PostTag = db.Table(
    "PostTag",
    db.Column(
        "post_id", UUID(as_uuid=True), db.ForeignKey("Post.id", ondelete="CASCADE")
    ),
    db.Column(
        "tag_id", UUID(as_uuid=True), db.ForeignKey("Tag.id", ondelete="CASCADE")
    ),
)


class Post(db.Model):
    __tablename__ = "Post"

    id = db.Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        unique=True,
        nullable=False,
        server_default=db.text("(gen_random_uuid())"),
    )
    title = db.Column(db.String(120), nullable=False)
    content = db.Column(db.Text, nullable=False)
    image_url = db.Column(db.String(120))
    is_delete = db.Column(db.Boolean, default=False)
    status = db.Column(db.Enum(PostStatus), nullable=False)
    updated_at = db.Column(
        db.DateTime(timezone=True), nullable=False, server_default=db.func.now()
    )
    created_at = db.Column(
        db.DateTime(timezone=True), nullable=False, server_default=db.func.now()
    )

    # Foreign keys
    user_id = db.Column(
        UUID(as_uuid=True), db.ForeignKey("User.id", ondelete="CASCADE")
    )

    # relationship
    tags = db.relationship(
        "Tag",
        secondary=PostTag,
        backref="posts",
        lazy=True,
    )
    comments = db.relationship(
        "Comment", backref="commented_post", cascade="all, delete-orphan", lazy=True
    )

    post_notifications = db.relationship(
        "PostNotification",
        backref="notified_post_by_post",
        cascade="all, delete-orphan",
        lazy=True,
    )

    def __init__(self, post_dist, *args, **kwargs):
        self.title = post_dist.get("title")
        self.content = post_dist.get("content")
        self.image_url = post_dist.get("image_url")
        self.status = PostStatus.PENDING
        self.created_at = post_dist.get("created_at")
        self.updated_at = self.created_at

    def __repr__(self):
        return f"<{self.status} - {self.title[:40]}{'...' if len(self.title) >= 40 else ''}>"

app/forms/postForms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SelectMultipleField
from wtforms.validators import DataRequired, Length, Optional, Length
from app.utils.form_utils import SubmitButtonField


class CreatePostForm(FlaskForm):
    title = StringField(
        "Title",
        validators=[
            DataRequired(message="Title is required."),
            Length(max=120, message="Title must be less than 120 characters"),
        ],
    )
    tags = SelectMultipleField(
        "Tags",
        choices=[],
        validators=[
            Length(
                max=5,
                message="You can only select up to 5 tags.",
            ),
            Optional(),
        ],
    )
    content = TextAreaField(
        "Content",
        validators=[
            DataRequired(message="Content is required."),
            Length(max=15000, message="Content must be less than 15000 characters"),
        ],
    )
    image = FileField(
        "Image",
        validators=[
            FileAllowed(
                ["png", "jpg", "jpeg", "gif"],
                message="Only support png, jpg, jpeg, gif files.",
            ),
            Optional(),
        ],
    )
    submit = SubmitButtonField("Post")

    def set_tag_choices(self):
        from app.models.tag import Tag

        self.tags.choices = [(tag.name, tag.name) for tag in Tag.query.all()]

app/post/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SelectMultipleField
from wtforms.validators import DataRequired, Length, Optional, Length
from app.utils.form_utils import SubmitButtonField

class CreatePostForm(FlaskForm):
    title = StringField(
        "Title",
        validators=[
            DataRequired(),
            Length(max=120, message="Title must be less than 120 characters"),
        ],
    )
    tags = SelectMultipleField(
        "Tags",
        choices=[],
        validators=[
            Length(
                max=5,
                message="You can only select up to 5 tags.",
            ),
            Optional(),
        ],
    )
    content = TextAreaField("Content", validators=[DataRequired()])
    image_url = FileField(
        "Image",
        validators=[
            FileAllowed(
                ["png", "jpg", "jpeg", "gif"],
                message="Only support png, jpg, jpeg, gif files.",
            ),
            Optional(),
        ],
    )
    submit = SubmitButtonField("Post")

    def set_tag_choices(self):
        from app.models.tag import Tag

        self.tags.choices = [(tag.name, tag.name) for tag in Tag.query.all()]

app/me/__init__.py
from flask import Blueprint

me_bp = Blueprint("me", __name__, url_prefix="/me")

from . import views

app/me/views.py
from flask import render_template, redirect, url_for, request, flash
from flask_login import current_user

from . import me_bp
from app import app, db
from app.services.me_service import get_user_agg_interaction
from app.utils.helper import upload_image, delete_image
from app.utils.decorators import login_required, require_accept_community_guideline

notSourceHandlerMessages = {
    "postsPage": {
        "messageTitles": [
            "No posts yet!",
        ],
        "messageBodies": [
            "Start sharing your thoughts with the world.",
        ],
    },
    "likesPage": {
        "messageTitles": [
            "No liked posts yet!",
        ],
        "messageBodies": [
            "Explore and like posts that you enjoy.",
        ],
    },
    "repliesPage": {
        "messageTitles": [
            "No replies yet!",
        ],
        "messageBodies": [
            "Join the conversation by replying to posts.",
        ],
    },
    "bookmarksPage": {
        "messageTitles": [
            "No bookmarks yet!",
        ],
        "messageBodies": [
            "Save posts that you find interesting to read later.",
        ],
    },
    "rejectedPostsPage": {
        "messageTitles": [
            "No rejected posts yet!",
        ],
        "messageBodies": [
            "All your posts are approved and visible.",
        ],
    },
}


@me_bp.route("/", methods=["GET", "POST"])
@login_required
@require_accept_community_guideline
def index():

    if request.method == "POST":
        avatar = request.files["avatar"]
        if not avatar:
            flash("No file is selected", "warning")
            return redirect(url_for("me.index"))

        avatar_url = upload_image(avatar, app.config["CLOUDINARY_AVATAR_IMAGE_FOLDER"])
        if not avatar_url:
            flash("Failed to upload the avatar", "warning")
            return redirect(url_for("me.index"))

        if current_user.avatar_url:
            is_deleted = delete_image(current_user.avatar_url)

            if not is_deleted:
                flash("Failed to upload the avatar", "warning")
                return redirect(url_for("me.index"))

        current_user.avatar_url = avatar_url
        current_user.updated_at = db.func.now()
        db.session.commit()
        flash("Avatar updated successfully", "success")

    return redirect(url_for("me.posts"))


@me_bp.route("/posts", methods=["GET", "POST"])
@login_required
@require_accept_community_guideline
def posts():
    userAggInteraction = get_user_agg_interaction(current_user)

    return render_template(
        "me/posts.html",
        user=current_user,
        userAggInteraction=userAggInteraction,
        postContainerId="myPageCreatedPostCardContainer",
        notSourceHandlerMessages=notSourceHandlerMessages["postsPage"],
    )


@me_bp.route("/likes")
@login_required
@require_accept_community_guideline
def likes():
    userAggInteraction = get_user_agg_interaction(current_user)

    return render_template(
        "me/posts.html",
        user=current_user,
        userAggInteraction=userAggInteraction,
        postContainerId="myPageLikedPostCardContainer",
        notSourceHandlerMessages=notSourceHandlerMessages["likesPage"],
    )


@me_bp.route("/replies")
@login_required
@require_accept_community_guideline
def replies():

    userAggInteraction = get_user_agg_interaction(current_user)

    return render_template(
        "me/posts.html",
        user=current_user,
        userAggInteraction=userAggInteraction,
        postContainerId="myPageRepliesPostCardContainer",
        notSourceHandlerMessages=notSourceHandlerMessages["repliesPage"],
    )


@me_bp.route("/bookmarks")
@login_required
@require_accept_community_guideline
def bookmarks():

    userAggInteraction = get_user_agg_interaction(current_user)

    return render_template(
        "me/posts.html",
        user=current_user,
        userAggInteraction=userAggInteraction,
        postContainerId="myPageBookmarkedPostCardContainer",
        notSourceHandlerMessages=notSourceHandlerMessages["bookmarksPage"],
    )


@me_bp.route("/rejected-posts")
@login_required
@require_accept_community_guideline
def rejected_posts():

    userAggInteraction = get_user_agg_interaction(current_user)

    return render_template(
        "me/posts.html",
        user=current_user,
        userAggInteraction=userAggInteraction,
        postContainerId="myPageRejectedPostCardContainer",
        notSourceHandlerMessages=notSourceHandlerMessages["rejectedPostsPage"],
        isRejected=True,
    )

app/post/__init__.py
from flask import Blueprint

post = Blueprint("post", __name__, url_prefix="/posts")

from . import views

app/post/views.py
from uuid import UUID
from flask import flash, redirect, url_for, render_template
from flask_login import current_user

from . import post
from app.models.post import Post, PostStatus
from app.models.user import User
from app.models.tag import Tag
from app.dto.post_dto import PostDTO
from app.utils.decorators import login_required, require_accept_community_guideline


@post.route("/<post_id>", methods=["GET"])
@login_required
@require_accept_community_guideline
def get_post(post_id):

    user = User.query.get(current_user.id)
    post = Post.query.get(UUID(post_id))

    if not post or post.is_delete:
        flash("Post not found", "error")
        return redirect(url_for("main.index"))

    postCreator = User.query.get(post.user_id)

    postDTO = PostDTO(post, postCreator, user)

    return render_template(
        "post/postDetail.html",
        post=postDTO.to_dict(),
        user=current_user,
        operation="read",
    )


@post.route("/new-post", methods=["GET"])
@login_required
@require_accept_community_guideline
def new_post():
    tags = Tag.query.all()
    tag_list = []
    for tag in tags:
        tag_list.append(
            {
                "id": tag.id,
                "name": tag.name,
                "color": tag.color,
            }
        )

    return render_template(
        "post/postDetail.html", user=current_user, tags=tag_list, operation="create"
    )


@post.route("/<post_id>/edit-post", methods=["GET"])
@login_required
@require_accept_community_guideline
def edit_post(post_id):
    post = Post.query.get(UUID(post_id))

    if not post or post.is_delete or post.status == PostStatus.PENDING:
        flash("Post not found", "error")
        return redirect(url_for("main.index"))

    tags = Tag.query.all()
    tag_list = []
    for tag in tags:
        tag_list.append({"id": tag.id, "name": tag.name, "color": tag.color})

    return render_template(
        "post/postDetail.html",
        user=current_user,
        tags=tag_list,
        operation="update",
        post=post,
    )

app/templates/me/posts.html
{% extends "layouts/loginedBase.html" %}

{% block title %}
  Posts
{% endblock title %}

{% block content %}
  <section class="container flex flex-col gap-16 py-12 user-info-section">
    <div class="flex gap-6 user-info-container">
      {% with avatar_url=user.avatar_url, class = 'avatar-lg', owner = user %}
        {% include "layouts/avatar.html" %}
      {% endwith %}
      <div class="flex flex-col">
        <div class="flex gap-4 user-info">
          <h2 class="text-headline-sm">Anonymous_{{ user.anon_no }}</h2>
          <div class="campus-tag">{{ user.campus.value }}</div>
        </div>
        <form
          action="{{ url_for('me.index') }}"
          method="post"
          enctype="multipart/form-data"
          class="flex gap-2"
          id="avatarForm"
        >
          <!-- CSRF token -->
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

          <button type="button" class="text-label-lg edit-avatar">
            Edit avatar
          </button>
          <div class="recommend-dimension">Recomend dimension 40 x 40</div>
          <input
            type="file"
            name="avatar"
            accept="image/*"
            id="avatar"
            class="hidden"
          />
          <label for="avatar" class="hidden">Avatar</label>
          <input
            type="submit"
            value="Upload Avatar"
            id="avatarSubmitButton"
            style="display: none;"
          />
        </form>
      </div>
    </div>
    <div class="flex flex-col gap-6 me-page-navigation-container">
      <nav class="user-content-container">
        <ul class="flex gap-8 text-headline-sm">
          <li class="user-content-item">
            <a
              href="{{ url_for('me.posts') }}"
              class="link
          {{ 'active' if request.path == url_for('me.posts') }}
          "
              >{{ userAggInteraction.createdPosts }} Posts</a
            >
          </li>
          <li class="user-content-item">
            <a
              href="{{ url_for('me.likes') }}"
              class="link
          {{ 'active' if request.path == url_for('me.likes') }}
          "
              >{{ userAggInteraction.likedPosts }} Likes</a
            >
          </li>
          <li class="user-content-item">
            <a
              href="{{ url_for('me.replies') }}"
              class="link
          {{ 'active' if request.path == url_for('me.replies') }}
          "
              >{{ userAggInteraction.commentsAndReplies }} Replies</a
            >
          </li>
          <li class="user-content-item">
            <a
              href="{{ url_for('me.bookmarks') }}"
              class="link
          {{ 'active' if request.path == url_for('me.bookmarks') }}
          "
              >{{ userAggInteraction.bookmarkedPosts }} Bookmarks</a
            >
          </li>
          <li class="user-content-item">
            <a
              href="{{ url_for('me.rejected_posts') }}"
              class="link
          {{ 'active' if request.path == url_for('me.rejected_posts') }}
          "
              >{{ userAggInteraction.rejectedPosts }} Rejects</a
            >
          </li>
        </ul>
      </nav>
      {% if isRejected %}
        <div class="text-label-lg rejected-page-info">
          Tips: You can resubmit or delete the rejected post
        </div>
      {% endif %}
    </div>
    <div
      class="flex flex-col px-4 gap-12 posts-container"
      id="{{ postContainerId }}"
    >
      {% include "layouts/postCardList.html" %}
      <div class="flex flex-center loading-container d-none">
        {% include "svgs/infinity-loading-spinner.html" %}
      </div>
      {% with svgImage="svgs/mePageNoContent.html", notSourceHandlerMessages = notSourceHandlerMessages %}
        {% include "layouts/noResourceHandler.html" %}
      {% endwith %}
    </div>
  </section>
{% endblock content %}

{% block js %}
  <script type="text/javascript">
    const avatar = document.querySelector("#avatar");
    const editAvatar = document.querySelector(".edit-avatar");
    const submitButton = document.querySelector("#avatarSubmitButton");

    editAvatar.addEventListener("click", () => {
      avatar.click();
    });

    avatar.addEventListener("change", () => {
      const file = avatar.files[0];
      if (file) {
        submitButton.click();
      }
    });
  </script>
{% endblock js %}